# Analyze Data for Quality and get preliminary Results

We test for validation of columns, quantity and quality of data points, ability to arrange data points such that analysis can be done via machine learning.

## Important Notes
This is not production quality code.  Code here is exploratory analytics code which needs to be wrapped up into proper functions as data differences and issues/exceptions are discovered.  This code can serve as reference for production code, but should not ever be treated as production code.  

In [1]:
#Key Libraries Required
import pandas as pd
import numpy as np

In [2]:
#Define data location & load data.
base_dir = "C:/Users/vmadmin/Documents/Work/spi/dataspi/"
good_file = "GOOD_aug27_redo.csv"
bad_file = "L7SPIresults_Defects_ONLY_query-impala-39690.csv"

good = pd.read_csv(base_dir + good_file)
bad = pd.read_csv(base_dir + bad_file)

In [3]:
#Get a feel for what is in the data.
good.head()

plcng_plant_cd  mach_id  pcb_side_inspd  wo_num  defct_dttm  intrvl_key  \
0             NaN      NaN             NaN     NaN         NaN         NaN   
1             NaN      NaN             NaN     NaN         NaN         NaN   
2             NaN      NaN             NaN     NaN         NaN         NaN   
3             NaN      NaN             NaN     NaN         NaN         NaN   
4             NaN      NaN             NaN     NaN         NaN         NaN   

   plcng_area_cd  plcng_prcs_cd  plcng_wrk_ctr_cd  fndng_plant_cd  \
0            NaN            NaN               NaN             NaN   
1            NaN            NaN               NaN             NaN   
2            NaN            NaN               NaN             NaN   
3            NaN            NaN               NaN             NaN   
4            NaN            NaN               NaN             NaN   

        ...        pad_stncl_hgt  pad_spi_result  pad_spi_defct_type  \
0       ...                  127            GOOD                GOOD   
1       ...                  127            GOOD                GOOD   
2       ...                  127            GOOD                GOOD   
3       ...                  127            GOOD                GOOD   
4       ...                  127            GOOD                GOOD   

   solder_paste_vol_pct solder_paste_hgt  solder_paste_area_pct  \
0              113.5076         153.6871               93.79748   
1              105.2033         137.0668               97.47670   
2              106.6394         163.5016               82.83224   
3              113.9531         148.7802               97.27131   
4              110.2563         148.6627               94.19012   

   cmpnt_part_num  pkg_type  stncl_surf_area_ratio    extract_dttm  
0     PN-27795-U5         0                 0.9055  8/28/2018 2:54  
1     PN-27795-U5         0                 0.9055  8/28/2018 2:54  
2     PN-27795-U5         0                 0.9055  8/28/2018 2:54  
3     PN-27795-U5         0                 0.9055  8/28/2018 2:54  
4     PN-27795-U5         0                 0.9055  8/28/2018 2:54  

[5 rows x 39 columns]

In [3]:
#Get a feel for what is in the bad data
bad.head()

plcng_plant_cd mach_id pcb_side_inspd      wo_num       defct_dttm  \
0            1020     FP9            TOP  4009351183  6/24/2018 15:56   
1            1020     FP9            TOP  4009376503    7/3/2018 8:56   
2            1020     FP9            TOP  4009376503    7/3/2018 8:56   
3            1020     FP9            TOP  4009376503   7/6/2018 14:51   
4            1020     FP9            TOP  4009376503   7/6/2018 14:51   

   intrvl_key plcng_area_cd        plcng_prcs_cd  plcng_wrk_ctr_cd  \
0  1529855100       TWB_SM3  TWB_PCBA_SM3_TOP_FP  TWB_PCBA_TOP_FP9   
1  1530607500       TWB_SM3  TWB_PCBA_SM3_TOP_FP  TWB_PCBA_TOP_FP9   
2  1530607500       TWB_SM3  TWB_PCBA_SM3_TOP_FP  TWB_PCBA_TOP_FP9   
3  1530888300       TWB_SM3  TWB_PCBA_SM3_TOP_FP  TWB_PCBA_TOP_FP9   
4  1530888300       TWB_SM3  TWB_PCBA_SM3_TOP_FP  TWB_PCBA_TOP_FP9   

   fndng_plant_cd       ...       solder_paste_offst_y_axis pad_stncl_hgt  \
0            1020       ...                          -11.45           127   
1            1020       ...                            0.92           127   
2            1020       ...                            4.82           127   
3            1020       ...                            1.51           127   
4            1020       ...                           -2.27           127   

  pad_spi_result pad_spi_defct_type solder_paste_vol_pct solder_paste_hgt  \
0           GOOD               GOOD             127.3716         165.5654   
1           GOOD               GOOD             130.2810         159.0643   
2           GOOD               GOOD             132.1127         160.2906   
3           GOOD               GOOD             130.4016         170.2945   
4           GOOD               GOOD             123.9029         166.4613   

  solder_paste_area_pct pkg_type stncl_surf_area_ratio    extract_dttm  
0              97.70272        0                0.9055  7/4/2018 13:15  
1             104.01890        0                0.9055  7/4/2018 14:17  
2             104.67440        0                0.9055  7/4/2018 14:17  
3              97.24921        0                0.9055  7/4/2018 14:19  
4              94.53050        0                0.9055  7/4/2018 14:19  

[5 rows x 38 columns]

In [4]:
#How many good/ bad do we have (pins)
print(good.shape)
print(bad.shape)

(89094, 39)
(33700, 38)


In [5]:
# See what full list of columns are and if there is a difference in columns between the two
print(good.columns.values)
print(list(set(good) - set(bad)))

['plcng_plant_cd' 'mach_id' 'pcb_side_inspd' 'wo_num' 'defct_dttm'
 'intrvl_key' 'plcng_area_cd' 'plcng_prcs_cd' 'plcng_wrk_ctr_cd'
 'fndng_plant_cd' 'fndng_area_cd' 'fndng_prcs_cd' 'bld_part_no'
 'bld_serial_no' 'barcd' 'assy_part_no' 'assy_serial_no' 'defct_cd'
 'failed_test_code' 'fail_type' 'cmpnt_part_no' 'spi_test_id' 'ref_id'
 'silkscrn_nbr' 'cmpntpin_nbr' 'cmpntpin_size_x_axis'
 'cmpntpin_size_y_axis' 'solder_paste_offst_x_axis'
 'solder_paste_offst_y_axis' 'pad_stncl_hgt' 'pad_spi_result'
 'pad_spi_defct_type' 'solder_paste_vol_pct' 'solder_paste_hgt'
 'solder_paste_area_pct' 'cmpnt_part_num' 'pkg_type'
 'stncl_surf_area_ratio' 'extract_dttm']
['cmpnt_part_num']


In [6]:
list(set(good) - set(bad))

['cmpnt_part_num']

In [7]:
def combine(x):
    r = x.split("-") 
    if(len(r) > 2):
        x = '-'.join(r[0:1])
    return x
bad["cmpnt_part_no"] = bad["cmpnt_part_no"].apply(lambda x: combine(x))

In [8]:
print(set(bad["barcd"]))
print(set(bad["silkscrn_nbr"]))
print(set(bad["ref_id"]))
print(set(bad["cmpnt_part_no"]))

{'00F01554', '00F4B44F', '00F6F7DB', '00F7DE52', '00F11F71', '00F6F799', '00F15471', '00F38E59', '00F87339', '00F11BC5', '00F5FD84', '00F7C4BD', '00F11AD9', '00F29AA2', '00F872D1', '00F11B29', '00F2970E', '00F40F3D', '00F11A77', '00F45F61', '00F40B7D', '00F151BF', '00F7C38B', '00F5FD50', '00F0BA04', '00F01822', '00F01806', '00F11C41', '00F11F8B', '00F5D9D9', '00F75A04', '00F015C0', '00F40BC9', '00F296AA', '00F29A28', '00F7C0F9', '00F86E67', '00F1562B', '00F7DED8', '00F21545', '00F11B0D', '00F7C077', '00F08C10', '00F40CAB', '00F0B9F4', '00F7C00F', '00F7BA65', '00F5DB75', '00F11BE7', '00F75C6A', '00F40F19', '00F11851', '00F75A70', '00F0B986', '00F019A4', '00F6F87D', '00F5D9D5', '00F409A1', '00F11909', '00F75A1C', '00F75C74', '00F69D9F', '00F7BBA3', '00F11ADD', '00F29678', '00F01584', '00F4B3F9', '00F39057', '00F0B7F2', '00F15277', '00F87211', '00F11D75', '00F38C71', '00F11AED', '00F87323', '00F5DA97', '00F407D7', '00F11AC7', '00F40B13', '00F29584', '00F4B2FB', '00F4B5DF', '00F75A7E', '00

# Group Bad Data and Get Data Counts For Each Component

We need to get a feel for how much data we actually have and which components we have a decent shot of dealing with using standard machine learning approaches.

It is possible to solve all components using non standard approaches; however deeper analysis will need to be done to validate the approaches which could be applied.  This should be done both at a theoretical and practical level.

In [9]:
#This looks at bad currently.  For good I need to change first groupby to use "cmpnt_part_num not "cmpnt_part_no".
bad_vals = []
for k, v in bad.groupby("cmpnt_part_no"):
    for k, v1 in v.groupby("barcd"):
        for k, v2 in v1.groupby("silkscrn_nbr"):
            for k, v3 in v2.groupby("ref_id"):
                for k, v4 in v3.groupby("defct_dttm"):
                    vals = v4.sort_values("cmpntpin_nbr")[["solder_paste_offst_x_axis", 
                                                       "solder_paste_offst_y_axis", 
                                                       "solder_paste_vol_pct",
                                                       "solder_paste_hgt",
                                                       "solder_paste_area_pct",
                                                        "ref_id",
                                                        "cmpntpin_nbr",
                                                        "cmpnt_part_no"]]
                    addition = {"defect" : True, "pin_data" : vals, 
                                "ref_id" : list(set(v4["ref_id"]))[0],
                               "cmpnt_part_no" : list(set(v4["cmpnt_part_no"]))[0]}
                    bad_vals.append(addition)

In [10]:
ref_ids = list(set(bad["cmpnt_part_no"]))
for ref_id in ref_ids:
    num_ids = len([x for x in bad_vals if x["cmpnt_part_no"] == ref_id])
    print("ref id: {} count: {}".format(ref_id, num_ids))

ref id: PN-27724 count: 27
ref id: PN-419257 count: 27
ref id: 94474092 count: 31
ref id: PN-31488 count: 23
ref id: PN-27795 count: 34
ref id: PN-271803 count: 10
ref id: PN-29537 count: 6
ref id: PN count: 3


# Group Good Data and Get Data Counts For Each Component

We need to get a feel for how much data we actually have and which components we have a decent shot of dealing with using standard machine learning approaches.

It is possible to solve all components using non standard approaches; however deeper analysis will need to be done to validate the approaches which could be applied.  This should be done both at a theoretical and practical level.

In [11]:
#This looks at bad currently.  For good I need to change first groupby to use "cmpnt_part_num not "cmpnt_part_no".
#good["cmpnt_part_num"] = good["cmpnt_part_num"].apply(lambda x: combine(x))
good_vals = []
for k, v in good.groupby("cmpnt_part_num"):
    for k, v1 in v.groupby("barcd"):
        for k, v2 in v1.groupby("silkscrn_nbr"):
            for k, v3 in v2.groupby("ref_id"):
                for k, v4 in v3.groupby("spi_test_id"):
                    vals = v4.sort_values("cmpntpin_nbr")[["solder_paste_offst_x_axis", 
                                                       "solder_paste_offst_y_axis", 
                                                       "solder_paste_vol_pct",
                                                       "solder_paste_hgt",
                                                       "solder_paste_area_pct",
                                                        "ref_id",
                                                        "cmpntpin_nbr",
                                                        "cmpnt_part_num"]]
                    addition = {"defect" : False, "pin_data" : vals, 
                                "ref_id" : list(set(v4["ref_id"]))[0],
                               "cmpnt_part_num" : list(set(v4["cmpnt_part_num"]))[0]}
                    good_vals.append(addition)

In [12]:
ref_ids = list(set(good["cmpnt_part_num"]))
for ref_id in ref_ids:
    num_ids = len([x for x in good_vals if x["cmpnt_part_num"] == ref_id])
    print("ref id: {} count: {}".format(ref_id, num_ids))

ref id: PN-27795-U5 count: 62
ref id: PN-27724 count: 62
ref id: 94474092 count: 62
ref id: 94485092 count: 186
ref id: PN-271803 count: 186
ref id: PN-31488-U6 count: 62


# Experimental Section - Get Numpy Arrays for what I Need

This section is about extracting the numpy arrays for what we need and dealing with encoding stuff to numerical features if necessary.

We are focusing on component PN-27795 which exists ONLY for ref_id U5

In [13]:
good_27795 = [x for x in good_vals if x["cmpnt_part_num"] == 'PN-271803']
bad_27795 = [x for x in bad_vals if x["cmpnt_part_no"] == 'PN-271803']

print(len(good_27795))
print(len(bad_27795))

186
10


In [14]:
good_27795.describe()

AttributeError: 'list' object has no attribute 'describe'

In [15]:
good_27795 = good_27795[0:20]

In [16]:
print(len(good_27795))
print(len(bad_27795))

20
10


In [17]:
row_1 = good_27795[0]["pin_data"][["solder_paste_offst_x_axis", 
                                                       "solder_paste_offst_y_axis", 
                                                       "solder_paste_vol_pct",
                                                       "solder_paste_hgt",
                                                       "solder_paste_area_pct"]].values.flatten()
row_1 = np.append(row_1, [0])
print(row_1.shape)
row_2 = good_27795[1]["pin_data"][["solder_paste_offst_x_axis", 
                                                       "solder_paste_offst_y_axis", 
                                                       "solder_paste_vol_pct",
                                                       "solder_paste_hgt",
                                                       "solder_paste_area_pct"]].values.flatten()
row_2 = np.append(row_2, [0])
print(row_1.shape)

(421,)
(421,)


In [18]:
stacked = np.vstack([row_1, row_2])

In [19]:
stacked[0].shape

(421,)

In [20]:
stacked.shape

(2, 421)

# Convert to Data Shapes for Training

We will convert the good & bad to data shapes required for training and then do a train/test split to prep for a simplistic keras model

In [21]:
def get_ml_data(row, is_good):
    prep = row["pin_data"][["solder_paste_offst_x_axis", 
                            "solder_paste_offst_y_axis", 
                            "solder_paste_vol_pct",
                            "solder_paste_hgt",
                            "solder_paste_area_pct"]].values.flatten()
    if(is_good):
        prep = np.append(prep, [0.0])
    else:
        prep = np.append(prep, [1.0])
    return prep

good_complete_data = get_ml_data(good_27795.pop(0), is_good=True)
for data in good_27795:
    good_complete_data = np.vstack([good_complete_data, get_ml_data(data, is_good=True)])

In [22]:
good_complete_data.shape

(20, 421)

In [23]:
bad_complete_data = get_ml_data(bad_27795.pop(0), is_good=False)
for data in bad_27795:
    bad_complete_data = np.vstack([bad_complete_data, get_ml_data(data, is_good=False)])

In [24]:
bad_complete_data.shape

(10, 421)

In [25]:
bad_complete_data[0][:-1].reshape(16,16,5)[:][:][0].shape

ValueError: cannot reshape array of size 420 into shape (16,16,5)

In [26]:
full_data = np.append(bad_complete_data, good_complete_data, axis=0)
print(full_data.shape)

(30, 421)


In [27]:
#verify sizes for x vs y to extract input vs output.  Last column is the output or y value.
print(full_data[:,:-1].shape)
print(full_data[:,-1:].shape)

(30, 420)
(30, 1)


In [28]:
#prep for ml learning
from sklearn.model_selection import train_test_split

In [29]:
x_t, x_v, y_t, y_v = train_test_split(full_data[:,:-1], full_data[:,-1:], test_size = 0.50)
print(x_t.shape)
print(y_t.shape)
print(x_v.shape)
print(y_v.shape)

(15, 420)
(15, 1)
(15, 420)
(15, 1)


In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_t_scaled = scaler.fit_transform(x_t)

In [31]:
x_v_scaled = scaler.transform(x_v)
print(x_v_scaled)
print(x_v)
print(y_v.flatten())

[[ 0.01151067 -0.38258273  0.1978501  ...  0.87734942  0.58955527
   0.4376862 ]
 [-0.40506608 -0.2570002   1.48125707 ...  2.38139035  0.48955193
   2.5771568 ]
 [-0.78875519 -0.52719291 -0.56446829 ... -0.76943409 -1.9077474
   1.50377731]
 ...
 [-0.50783995 -0.19420894  0.59877102 ... -1.35064317 -1.73068249
   0.32798257]
 [-0.54620886 -0.18850064 -1.12210297 ...  0.63165815  0.05589836
   0.78278563]
 [ 0.60211785  0.35188478 -0.41811778 ...  0.09161451 -1.25007361
   1.82952129]]
[[ -4.92     -8.4     112.1399  ... 116.2529  165.1933   89.37478]
 [ -7.96     -7.74    122.1835  ... 128.0414  164.1576   99.05883]
 [-10.76     -9.16    106.1742  ... 103.3456  139.3296   94.20031]
 ...
 [ -8.71     -7.41    115.2774  ...  98.79015 141.1634   88.87822]
 [ -8.99     -7.38    101.8103  ... 114.3272  159.6664   90.93683]
 [ -0.61     -4.54    107.3195  ... 110.0944  146.1409   95.67475]]
[0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Classical Machine Learning

Lets set a benchmark with classical machine learning from scikit.  We should see some level of performance from this.

In [32]:
from sklearn.svm import SVC

In [33]:
svm = SVC()
svm.fit(x_t_scaled, y_t)

C:\Anaconda\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [34]:
v_p = svm.predict(x_v_scaled)

In [35]:
from sklearn.metrics import classification_report, confusion_matrix

In [37]:
print(classification_report(y_v.flatten(), v_p))
print(confusion_matrix(y_v.flatten(), v_p))
print(v_p.flatten())

             precision    recall  f1-score   support

        0.0       0.79      0.92      0.85        12
        1.0       0.00      0.00      0.00         3

avg / total       0.63      0.73      0.68        15

[[11  1]
 [ 3  0]]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Try a Random Forest Classifier

Just another model to give a whirl at.

In [40]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(x_t_scaled, y_t)
v_p = rfc.predict(x_v_scaled)

C:\Anaconda\lib\site-packages\ipykernel\__main__.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


In [42]:
print(classification_report(y_v.flatten(), v_p))
print(confusion_matrix(y_v.flatten(), v_p))
print(v_p.flatten())

             precision    recall  f1-score   support

        0.0       0.80      1.00      0.89        12
        1.0       0.00      0.00      0.00         3

avg / total       0.64      0.80      0.71        15

[[12  0]
 [ 3  0]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


C:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Keras Dense Neural Network

Lets give a shot at a dense neural network and see if we can get any decent results

In [43]:
import keras
from keras.models import Model, Sequential, load_model
from keras.layers import Input, Dense, Dropout, Conv2D, Flatten, MaxPooling2D
from keras.regularizers import L1L2
from keras.callbacks import EarlyStopping

C:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [44]:
x_t.shape

(15, 420)

In [45]:
model = None
INPUT_SIZE = (420,)
reg_rate = 0.001
model_in = Input(shape=INPUT_SIZE)
classifier = Dense(128, activation="tanh", kernel_regularizer=L1L2(l1=reg_rate, l2=reg_rate))(model_in)
classifier = Dense(64, activation="tanh", kernel_regularizer=L1L2(l1=reg_rate, l2=reg_rate))(classifier)
classifier = Dense(32, activation="tanh", kernel_regularizer=L1L2(l1=reg_rate, l2=reg_rate))(classifier)
#classifier = Dropout(0.5)(classifier)
classifier = Dense(1, activation="sigmoid", kernel_regularizer=L1L2(l1=reg_rate, l2=reg_rate))(classifier)

model = Model(inputs=[model_in], outputs=[classifier])
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["binary_accuracy"])

EPOCHS = 100
BATCH_SIZE = 20

callbacks = [ EarlyStopping(monitor="loss", patience=50, min_delta=0.0)]

evaluation = model.fit(x_t_scaled, y_t, shuffle=True,
                        epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=1,
                        validation_data = (x_v_scaled, y_v),
                        callbacks=callbacks)

Train on 15 samples, validate on 15 samples
Epoch 1/100
15/15 [==============================] - 0s 33ms/step - loss: 4.8478 - binary_accuracy: 0.4000 - val_loss: 4.7559 - val_binary_accuracy: 0.6000
Epoch 2/100
15/15 [==============================] - 0s 379us/step - loss: 4.5629 - binary_accuracy: 0.8667 - val_loss: 4.7254 - val_binary_accuracy: 0.6667
Epoch 3/100
15/15 [==============================] - 0s 201us/step - loss: 4.4010 - binary_accuracy: 1.0000 - val_loss: 4.7127 - val_binary_accuracy: 0.6667
Epoch 4/100
15/15 [==============================] - 0s 266us/step - loss: 4.2958 - binary_accuracy: 1.0000 - val_loss: 4.7076 - val_binary_accuracy: 0.6667
Epoch 5/100
15/15 [==============================] - 0s 200us/step - loss: 4.2192 - binary_accuracy: 1.0000 - val_loss: 4.7056 - val_binary_accuracy: 0.6667
Epoch 6/100
15/15 [==============================] - 0s 200us/step - loss: 4.1583 - binary_accuracy: 1.0000 - val_loss: 4.7046 - val_binary_accuracy: 0.6667
Epoch 7/100
15/

Epoch 53/100
15/15 [==============================] - 0s 800us/step - loss: 2.2315 - binary_accuracy: 1.0000 - val_loss: 3.3426 - val_binary_accuracy: 0.6667
Epoch 54/100
15/15 [==============================] - 0s 267us/step - loss: 2.1955 - binary_accuracy: 1.0000 - val_loss: 3.3047 - val_binary_accuracy: 0.6667
Epoch 55/100
15/15 [==============================] - 0s 200us/step - loss: 2.1599 - binary_accuracy: 1.0000 - val_loss: 3.2671 - val_binary_accuracy: 0.6667
Epoch 56/100
15/15 [==============================] - 0s 200us/step - loss: 2.1246 - binary_accuracy: 1.0000 - val_loss: 3.2296 - val_binary_accuracy: 0.6667
Epoch 57/100
15/15 [==============================] - 0s 267us/step - loss: 2.0896 - binary_accuracy: 1.0000 - val_loss: 3.1923 - val_binary_accuracy: 0.6667
Epoch 58/100
15/15 [==============================] - 0s 333us/step - loss: 2.0550 - binary_accuracy: 1.0000 - val_loss: 3.1550 - val_binary_accuracy: 0.6667
Epoch 59/100
15/15 [==============================] 

In [46]:
v_p_k = model.predict(x_v_scaled)
v_p_k = [1.0 if v  >= 0.5 else 0.0 for v in v_p_k]
print(classification_report(y_v.flatten(), v_p_k))
print(confusion_matrix(y_v.flatten(), v_p_k))
print(v_p_k)

             precision    recall  f1-score   support

        0.0       0.77      0.83      0.80        12
        1.0       0.00      0.00      0.00         3

avg / total       0.62      0.67      0.64        15

[[10  2]
 [ 3  0]]
[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


# Keras Sequential Model Compostion

Same as above just with sequential model composition

In [47]:
model = Sequential()
model.add(Dense(128,activation="relu",input_shape=(x_t.shape[1],)))
model.add(Dense(64,activation="relu"))
model.add(Dense(32,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["binary_accuracy"])

epoch_count=10
batch_size=10

history = model.fit(x=x_t_scaled,y=y_t,batch_size=batch_size,epochs=epoch_count)

Epoch 1/10
15/15 [==============================] - 0s 26ms/step - loss: 0.5595 - binary_accuracy: 0.8000
Epoch 2/10
15/15 [==============================] - 0s 404us/step - loss: 0.2596 - binary_accuracy: 0.9333
Epoch 3/10
15/15 [==============================] - 0s 852us/step - loss: 0.1463 - binary_accuracy: 1.0000
Epoch 4/10
15/15 [==============================] - 0s 337us/step - loss: 0.0893 - binary_accuracy: 1.0000
Epoch 5/10
15/15 [==============================] - 0s 332us/step - loss: 0.0541 - binary_accuracy: 1.0000
Epoch 6/10
15/15 [==============================] - 0s 401us/step - loss: 0.0346 - binary_accuracy: 1.0000
Epoch 7/10
15/15 [==============================] - 0s 733us/step - loss: 0.0215 - binary_accuracy: 1.0000
Epoch 8/10
15/15 [==============================] - 0s 533us/step - loss: 0.0151 - binary_accuracy: 1.0000
Epoch 9/10
15/15 [==============================] - 0s 467us/step - loss: 0.0099 - binary_accuracy: 1.0000
Epoch 10/10
15/15 [===================

In [49]:
v_p_k = model.predict(x_v_scaled)
v_p_k = [1.0 if v  >= 0.5 else 0.0 for v in v_p_k]
print(classification_report(y_v.flatten(), v_p_k))
print(confusion_matrix(y_v.flatten(), v_p_k))
print(v_p_k)

             precision    recall  f1-score   support

        0.0       0.79      0.92      0.85        12
        1.0       0.00      0.00      0.00         3

avg / total       0.63      0.73      0.68        15

[[11  1]
 [ 3  0]]
[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


# Keras Convolutional Neural Network

As the problem may be a pattern problem; lets give a whirl at a convolutional network

In [50]:
print(x_t.shape)
print(y_t.shape)
print(x_v.shape)
print(y_v.shape)

(15, 420)
(15, 1)
(15, 420)
(15, 1)


In [51]:
x_t_c = x_t_scaled.reshape(15, 14, 6, 5)
x_v_c = x_v_scaled.reshape(15, 14, 6, 5)

In [52]:
INPUT_SIZE = (14, 6, 5)
reg_rate = 0.001
model_in = Input(shape=INPUT_SIZE)
classifier = Conv2D(128, (3,3), activation="tanh", kernel_regularizer=L1L2(l1=reg_rate, l2=reg_rate))(model_in)
classifier = MaxPooling2D(pool_size=(2, 2), strides=(2, 2))(classifier)
classifier = Conv2D(64, (2,2), activation="tanh", kernel_regularizer=L1L2(l1=reg_rate, l2=reg_rate))(classifier)
#classifier = MaxPooling2D(pool_size=(2, 2), strides=(2, 2))(classifier)
classifier = Flatten()(classifier)
classifier = Dense(1, activation="sigmoid", kernel_regularizer=L1L2(l1=reg_rate, l2=reg_rate))(classifier)

model = Model(inputs=[model_in], outputs=[classifier])
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])

In [53]:
EPOCHS = 200
BATCH_SIZE = 20
callbacks = [ EarlyStopping(monitor="loss", patience=10, min_delta=0.0) ]

evaluation = model.fit(x_t_c, y_t, shuffle=True,
                        epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=1,
                        validation_data = (x_v_c, y_v),
                        callbacks=callbacks)

Train on 15 samples, validate on 15 samples
Epoch 1/200
15/15 [==============================] - 0s 30ms/step - loss: 2.4251 - acc: 0.5333 - val_loss: 2.3995 - val_acc: 0.7333
Epoch 2/200
15/15 [==============================] - 0s 464us/step - loss: 2.2427 - acc: 0.8667 - val_loss: 2.4042 - val_acc: 0.7333
Epoch 3/200
15/15 [==============================] - 0s 397us/step - loss: 2.1282 - acc: 0.9333 - val_loss: 2.3923 - val_acc: 0.7333
Epoch 4/200
15/15 [==============================] - 0s 397us/step - loss: 2.0430 - acc: 1.0000 - val_loss: 2.3817 - val_acc: 0.7333
Epoch 5/200
15/15 [==============================] - 0s 467us/step - loss: 1.9752 - acc: 1.0000 - val_loss: 2.3802 - val_acc: 0.7333
Epoch 6/200
15/15 [==============================] - 0s 531us/step - loss: 1.9202 - acc: 1.0000 - val_loss: 2.3854 - val_acc: 0.7333
Epoch 7/200
15/15 [==============================] - 0s 472us/step - loss: 1.8739 - acc: 1.0000 - val_loss: 2.3924 - val_acc: 0.7333
Epoch 8/200
15/15 [=======

Epoch 62/200
15/15 [==============================] - 0s 467us/step - loss: 0.7150 - acc: 1.0000 - val_loss: 1.5122 - val_acc: 0.7333
Epoch 63/200
15/15 [==============================] - 0s 401us/step - loss: 0.7004 - acc: 1.0000 - val_loss: 1.4983 - val_acc: 0.7333
Epoch 64/200
15/15 [==============================] - 0s 381us/step - loss: 0.6862 - acc: 1.0000 - val_loss: 1.4847 - val_acc: 0.7333
Epoch 65/200
15/15 [==============================] - 0s 467us/step - loss: 0.6721 - acc: 1.0000 - val_loss: 1.4716 - val_acc: 0.7333
Epoch 66/200
15/15 [==============================] - 0s 401us/step - loss: 0.6583 - acc: 1.0000 - val_loss: 1.4589 - val_acc: 0.7333
Epoch 67/200
15/15 [==============================] - 0s 467us/step - loss: 0.6446 - acc: 1.0000 - val_loss: 1.4468 - val_acc: 0.7333
Epoch 68/200
15/15 [==============================] - 0s 534us/step - loss: 0.6313 - acc: 1.0000 - val_loss: 1.4352 - val_acc: 0.7333
Epoch 69/200
15/15 [==============================] - 0s 466us

Epoch 123/200
15/15 [==============================] - 0s 466us/step - loss: 0.2545 - acc: 1.0000 - val_loss: 1.2000 - val_acc: 0.6000
Epoch 124/200
15/15 [==============================] - 0s 400us/step - loss: 0.2520 - acc: 1.0000 - val_loss: 1.2006 - val_acc: 0.6000
Epoch 125/200
15/15 [==============================] - 0s 400us/step - loss: 0.2495 - acc: 1.0000 - val_loss: 1.2011 - val_acc: 0.6000
Epoch 126/200
15/15 [==============================] - 0s 400us/step - loss: 0.2471 - acc: 1.0000 - val_loss: 1.2013 - val_acc: 0.6000
Epoch 127/200
15/15 [==============================] - 0s 399us/step - loss: 0.2448 - acc: 1.0000 - val_loss: 1.2015 - val_acc: 0.6000
Epoch 128/200
15/15 [==============================] - 0s 467us/step - loss: 0.2425 - acc: 1.0000 - val_loss: 1.2019 - val_acc: 0.6000
Epoch 129/200
15/15 [==============================] - 0s 467us/step - loss: 0.2402 - acc: 1.0000 - val_loss: 1.2025 - val_acc: 0.6000
Epoch 130/200
15/15 [==============================] - 

Epoch 184/200
15/15 [==============================] - 0s 466us/step - loss: 0.1628 - acc: 1.0000 - val_loss: 1.2998 - val_acc: 0.6000
Epoch 185/200
15/15 [==============================] - 0s 333us/step - loss: 0.1618 - acc: 1.0000 - val_loss: 1.3020 - val_acc: 0.6000
Epoch 186/200
15/15 [==============================] - 0s 467us/step - loss: 0.1609 - acc: 1.0000 - val_loss: 1.3042 - val_acc: 0.6000
Epoch 187/200
15/15 [==============================] - 0s 401us/step - loss: 0.1599 - acc: 1.0000 - val_loss: 1.3068 - val_acc: 0.6000
Epoch 188/200
15/15 [==============================] - 0s 401us/step - loss: 0.1590 - acc: 1.0000 - val_loss: 1.3092 - val_acc: 0.6000
Epoch 189/200
15/15 [==============================] - 0s 399us/step - loss: 0.1580 - acc: 1.0000 - val_loss: 1.3116 - val_acc: 0.6000
Epoch 190/200
15/15 [==============================] - 0s 533us/step - loss: 0.1571 - acc: 1.0000 - val_loss: 1.3137 - val_acc: 0.6000
Epoch 191/200
15/15 [==============================] - 

In [54]:
v_p_kc = model.predict(x_v_c)
v_p_kc = [1.0 if v  >= 0.5 else 0.0 for v in v_p_kc]
print(classification_report(y_v.flatten(), v_p_kc))
print(confusion_matrix(y_v.flatten(), v_p_kc))
print(v_p_kc)

             precision    recall  f1-score   support

        0.0       0.75      0.75      0.75        12
        1.0       0.00      0.00      0.00         3

avg / total       0.60      0.60      0.60        15

[[9 3]
 [3 0]]
[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [106]:
v_p_k

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]